import { StyleSheet, Platform } from 'react-native';
import { colors, radius, spacing, typography } from '../../../shared/constants/theme';

// ── Neon Blue theme ──────────────────────────────────────────────────────────
export const NEON = '#00f7ff'; // light neon blue (cyan)
export const NEON_DIM = 'rgba(0,247,255,0.15)'; // light tinted bg for buttons

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  map: { flex: 1 },

  searchContainer: {
    position: 'absolute',
    left: spacing.md,
    right: 68, // keep clear of 44px Options btn + spacing.md
    zIndex: 20,
  },

  // Right button column (satellite / traffic / voice)
  rightBtnCol: {
    position: 'absolute',
    right: spacing.md,
    gap: spacing.xs,
    zIndex: 20,
  },
  mapBtn: {
    width: 44,
    height: 44,
    borderRadius: 50,
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: NEON,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 12,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.95,
    shadowRadius: 8,
  },
  mapBtnOff: { opacity: 0.4 },
  mapBtnText: { fontSize: 20 },

  // Navigation top panel — wrapper handles absolute positioning for both
  // simple banner (>800 m) and the junction sign panel (<800 m)
  signWrap: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    zIndex: 20,
  },
  navBanner: {
    backgroundColor: 'rgba(0,10,30,0.88)',
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    elevation: 14,
    borderWidth: 2,
    borderColor: NEON,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.90,
    shadowRadius: 10,
  },
  navArrow: { fontSize: 36, marginRight: spacing.md },
  navBannerBody: { flex: 1 },
  navStreet: { fontSize: 18, fontWeight: '700', color: colors.text },
  navNext: { ...typography.caption, color: colors.textSecondary, marginTop: 3 },

  // Lane Assistance — enlarged road-style lane boxes
  laneAssistWrap: { marginTop: 6, alignItems: 'center' },
  laneAssistLabel: {
    fontSize: 9,
    color: 'rgba(0,191,255,0.70)',
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  laneRow: { flexDirection: 'row', gap: 4, alignSelf: 'center' },
  laneBox: {
    width: 36,
    height: 48,
    backgroundColor: 'rgba(10, 15, 30, 0.85)',
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  laneBoxActive: {
    backgroundColor: 'rgba(0,191,255,0.28)',
    borderColor: NEON,
    borderWidth: 2.5,
  },
  laneArrow: { fontSize: 20, opacity: 0.30 },
  laneArrowActive: { opacity: 1 },

  // Sygic-style absolute lane strip — bottom of screen, < 500 m from turn
  laneStrip: {
    position: 'absolute',
    bottom: 210,
    alignSelf: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,8,20,0.88)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: NEON,
    paddingHorizontal: 12,
    paddingVertical: 8,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 18,
    zIndex: 20,
  },
  laneStripLabel: {
    color: NEON,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    opacity: 0.85,
  },
  laneStripCells: {
    flexDirection: 'row',
    gap: 4,
  },
  laneSCell: {
    width: 48,
    height: 62,
    borderRadius: 7,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  laneSCellActive: {
    // backgroundColor + shadowOpacity are animated via laneGlowBg / laneGlowShadow
    borderColor: NEON,
    borderWidth: 3,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 14,
    elevation: 10,
    transform: [{ scale: 1.10 }],   // 3D "pop out" — active lane appears closer
  },
  laneSCellArrow:       { fontSize: 26, opacity: 0.35 },
  laneSCellArrowActive: { fontSize: 26, opacity: 1 },

  // Truck geometry badge — amber pill showing active routing constraints
  truckDimRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
    justifyContent: 'center',
  },
  truckDimBadge: {
    backgroundColor: 'rgba(255,170,0,0.12)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(0,191,255,0.6)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  truckDimText: { fontSize: 10, color: '#ffaa00', fontWeight: '600' },
  adrBadge: {
    borderColor: '#ff8c00',
    backgroundColor: 'rgba(255,140,0,0.18)',
    shadowColor: '#ff8c00',
    shadowOpacity: 0.8,
    shadowRadius: 6,
  },

  // ── Tilequery UI ────────────────────────────────────────────────────────────

  // Elevation chip — floating, bottom-left
  elevationChip: {
    position: 'absolute',
    left: spacing.md,
    backgroundColor: 'rgba(0,20,40,0.82)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,191,255,0.35)',
    paddingHorizontal: 9,
    paddingVertical: 3,
    zIndex: 15,
  },
  elevationText: { fontSize: 11, color: NEON, fontWeight: '700', letterSpacing: 0.5 },

  // Tunnel / bridge warning banner — full-width amber strip
  tunnelWarnBanner: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 30,
    backgroundColor: 'rgba(220, 100, 0, 0.93)',
    paddingVertical: 7,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
  },
  tunnelWarnText: { fontSize: 13, color: '#fff', fontWeight: '700', textAlign: 'center', fontFamily: Platform.OS === 'android' ? 'Roboto' : 'Arial' },

  // Auto-parking toast — card that slides up when stationary
  autoParkToast: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    backgroundColor: 'rgba(0,8,24,0.95)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,191,255,0.25)',
    padding: spacing.sm,
    zIndex: 25,
  },
  autoParkHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  autoParkTitle: { fontSize: 12, color: NEON, fontWeight: '700' },
  autoParkClose: { fontSize: 14, color: colors.textSecondary, paddingHorizontal: 4 },
  autoParkItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  autoParkName: { flex: 1, fontSize: 12, color: colors.text, marginRight: 8 },
  autoParkDist: { fontSize: 11, color: NEON, fontWeight: '600' },

  // GPS chip
  gpsChip: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: 'rgba(22,33,62,0.9)',
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.full,
    zIndex: 15,
  },
  gpsText: { ...typography.label, color: colors.textSecondary },

  // Re-routing chip
  reroutingChip: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: 'rgba(40,30,10,0.95)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.warning,
    zIndex: 25,
    elevation: 10,
  },
  reroutingText: { ...typography.label, color: colors.warning },

  // Vehicle badge
  badge: {
    position: 'absolute',
    left: spacing.md,
    backgroundColor: 'rgba(26,26,46,0.88)',
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.accent,
    zIndex: 15,
  },
  badgeText: { ...typography.label, color: colors.text, fontWeight: '700' },

  pin: { alignItems: 'center' },
  pinEmoji: { fontSize: 30 },
  starPin: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#FFD700',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FF8C00',
    width: 32,
    height: 32,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
    elevation: 12,
  },
  starPinEmoji: { fontSize: 18, lineHeight: 22 },

  loadingChip: {
    position: 'absolute',
    bottom: 160,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: 'rgba(22,33,62,0.95)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    elevation: 8,
  },
  loadingText: { ...typography.caption, color: colors.textSecondary },

  // POI markers on map
  poiMarker: {
    backgroundColor: 'rgba(15,15,30,0.85)',
    borderRadius: radius.full,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.accentLight,
  },
  poiMarkerEmoji: { fontSize: 18 },

  // POI category bar
  poiBar: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    gap: spacing.xs,
    zIndex: 18,
  },
  poiCatBtn: {
    flex: 1,
    backgroundColor: NEON_DIM,
    borderRadius: 50,
    paddingVertical: 6,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: NEON,
    elevation: 8,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  poiCatBtnActive: {
    borderColor: NEON,
    backgroundColor: 'rgba(0,191,255,0.2)',
    shadowColor: NEON,
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 12,
  },
  poiCatEmoji: { fontSize: 18 },
  poiCatLabel: { ...typography.label, color: colors.textSecondary, fontSize: 9, marginTop: 1 },

  // POI results list
  poiListContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 18,
  },
  poiListContent: { paddingHorizontal: spacing.sm },
  poiLoading: { alignSelf: 'center', marginBottom: spacing.xs },
  poiCard: {
    backgroundColor: 'rgba(22,33,62,0.95)',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginRight: spacing.sm,
    width: 120,
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 6,
  },
  poiCardEmoji: { fontSize: 22, marginBottom: 2 },
  poiCardName: { ...typography.label, color: colors.text, fontWeight: '700', fontSize: 11 },
  poiCardBrand: { ...typography.label, color: colors.accent, fontSize: 10, marginTop: 1 },
  poiCardAddr: { ...typography.label, color: colors.textMuted, fontSize: 9, marginTop: 2 },
  poiCardSAR: {
    borderColor: '#ff8c00',
    shadowColor: '#ff8c00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 6,
  },

  // Parking cards panel (from GPT-4o show_parking action)
  parkingPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 19,
    backgroundColor: '#091529',          // тъмно синьо header strip
    paddingBottom: 8,
    borderTopWidth: 1.5,
    borderTopColor: '#1a8fd1',
  },
  parkingPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  parkingPanelTitle: {
    ...typography.label,
    color: '#60c0ff',                    // светло синьо заглавие
    fontWeight: '800',
    fontSize: 13,
  },
  parkingDismissBtn: { padding: 4 },
  parkingDismissTxt: { color: colors.textSecondary, fontSize: 14 },
  parkingListContent: { paddingHorizontal: spacing.sm, paddingBottom: spacing.xs },
  parkingCard: {
    backgroundColor: '#0d1e3d',          // тъмно синьо, плътно
    borderRadius: radius.md,
    padding: spacing.sm,
    marginRight: spacing.sm,
    width: 170,
    borderWidth: 2,
    borderColor: '#1a8fd1',              // синя рамка
    elevation: 12,
    shadowColor: '#1a8fd1',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.70,
    shadowRadius: 8,
  },
  parkingCardName: {
    ...typography.label,
    color: colors.text,
    fontWeight: '700',
    fontSize: 12,
    marginBottom: 3,
  },
  parkingCardDist: {
    ...typography.label,
    color: NEON,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  parkingBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 3, marginBottom: 5 },
  parkingBadge: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: radius.sm,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  parkingBadgePaid: { backgroundColor: 'rgba(239,68,68,0.15)' },
  parkingBadgeFree: { backgroundColor: 'rgba(34,197,94,0.15)' },
  parkingBadgeTxt: { color: colors.text, fontSize: 9 },
  parkingHours: {
    ...typography.label,
    color: colors.textMuted,
    fontSize: 9,
    marginBottom: 6,
  },
  parkingPin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,191,255,0.12)',
    borderWidth: 1.5,
    borderColor: NEON,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  parkingPinText: { fontSize: 16 },

  // HOS badge
  hosBadge: {
    backgroundColor: 'rgba(15,15,30,0.92)',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 4,
  },
  hosBadgeWarn:  { borderColor: colors.warning },
  hosBadgeLimit: { borderColor: colors.error },
  hosBadgeLabel: { ...typography.label, color: colors.textMuted, fontSize: 8 },
  hosBadgeValue: { fontSize: 14, fontWeight: '700', color: colors.text },

  // Bottom-left: speed
  speedRow: {
    position: 'absolute',
    left: spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
    zIndex: 15,
  },
  speedBox: {
    backgroundColor: 'rgba(15,15,30,0.92)',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    minWidth: 72,
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 6,
  },
  speedValue: { fontSize: 36, fontWeight: '800', color: colors.text },
  speedUnit:  { ...typography.label, color: colors.textSecondary },

  signColumn: {
    flexDirection: 'column',
    gap: 8,
    alignItems: 'center',
    marginBottom: 4,
  },
  noOvertakingCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    borderWidth: 5,
    borderColor: '#e00000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
  },
  noOvertakingEmoji: {
    fontSize: 22,
  },

  gradeCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    borderWidth: 5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
  },
  gradeEmoji: { fontSize: 14 },
  gradeVal: { fontSize: 12, fontWeight: '900', color: '#000' },

  speedCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#fff',
    borderWidth: 5,
    borderColor: '#e00000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.55,
    shadowRadius: 5,
    elevation: 12,
  },
  speedCircleExceeded: {
    borderColor: '#ff0000',
    backgroundColor: '#fff8f8',
    shadowColor: '#ff0000',
    shadowOpacity: 1,
    shadowRadius: 14,
  },
  speedCircleNum: {
    fontSize: 21,
    fontWeight: '900',
    color: '#111',
    letterSpacing: -0.5,
  },

  // Bottom-right: distance to turn
  distBox: {
    position: 'absolute',
    right: spacing.md,
    backgroundColor: 'rgba(15,15,30,0.92)',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    minWidth: 80,
    borderWidth: 1,
    borderColor: colors.accentLight,
    elevation: 6,
    zIndex: 15,
  },
  distValue: { fontSize: 20, fontWeight: '800', color: colors.accentLight },
  distLabel: { ...typography.label, color: colors.textSecondary, fontSize: 9 },

  // Bottom panel
  sheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.25)',
    marginBottom: 10,
  },
  bottomPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,8,20,0.94)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    elevation: 16,
    borderTopWidth: 1.5,
    borderColor: NEON,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.sm },
  infoCell: { flex: 1, alignItems: 'center' },
  infoLabel: { ...typography.label, color: colors.textMuted, marginBottom: 2 },
  infoValue: { fontSize: 18, fontWeight: '700', color: colors.text },
  infoDivider: {
    width: 1, height: 36,
    backgroundColor: colors.border,
    marginHorizontal: spacing.xs,
  },
  closeBtn: { position: 'absolute', right: 0, top: 0, padding: spacing.sm },
  closeBtnText: { color: colors.textSecondary, fontSize: 16 },

  shareBtn: {
    position: 'absolute',
    right: 36,
    top: 0,
    padding: spacing.sm,
  },
  shareBtnText: { color: NEON, fontSize: 18, fontWeight: '700' },

  // Border crossings panel
  borderPanel: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    top: 120,
    backgroundColor: 'rgba(18,18,38,0.97)',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: NEON,
    zIndex: 40,
    elevation: 16,
    paddingBottom: spacing.sm,
  },
  borderPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,191,255,0.20)',
  },
  borderPanelTitle: { ...typography.label, color: NEON, fontWeight: '700' },
  borderPanelClose: { color: colors.textSecondary, fontSize: 16, paddingLeft: spacing.md },
  borderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  borderFlag: { fontSize: 20, marginRight: spacing.sm },
  borderName: { ...typography.label, color: colors.text, flex: 1 },
  borderStatus: { ...typography.label, color: NEON, fontSize: 11 },
  destName: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  startBtn: {
    backgroundColor: 'rgba(120,0,0,0.18)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E53E3E',
    paddingVertical: 9,
    alignItems: 'center',
    marginBottom: spacing.xs,
    elevation: 8,
    shadowColor: '#E53E3E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  startBtnActive:   { backgroundColor: 'rgba(239,68,68,0.15)', borderColor: colors.error, shadowColor: colors.error },
  startBtnDisabled: { backgroundColor: 'rgba(22,33,62,0.5)', borderColor: colors.border, opacity: 0.6 },
  startBtnText: { ...typography.h3, color: colors.text },

  // Congestion chip
  congestionRow: { paddingHorizontal: spacing.xs, marginBottom: spacing.xs },
  congestionChip: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,160,0,0.15)',
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(0,160,0,0.4)',
  },
  congestionHeavy:   { backgroundColor: 'rgba(200,0,0,0.15)',   borderColor: 'rgba(200,0,0,0.4)' },
  congestionModerate:{ backgroundColor: 'rgba(200,140,0,0.15)', borderColor: 'rgba(200,140,0,0.4)' },
  congestionText: { ...typography.label, color: colors.text, fontSize: 11 },

  // Departure time chips
  departRow: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
    gap: spacing.xs,
  },
  departChip: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 50,
    backgroundColor: 'rgba(0,20,40,0.7)',
    borderWidth: 1.5,
    borderColor: 'rgba(0,191,255,0.3)',
    alignItems: 'center',
  },
  departChipActive: {
    backgroundColor: NEON_DIM,
    borderColor: NEON,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    elevation: 6,
  },
  departChipText:       { ...typography.label, color: colors.textSecondary, fontSize: 10 },
  departChipTextActive: { ...typography.label, color: colors.accent, fontWeight: '700', fontSize: 10 },

  fab: {
    position: 'absolute',
    right: spacing.md,
    width: 60,
    height: 60,
    borderRadius: 50,
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: NEON,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 14,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 10,
  },
  fabEmoji: { fontSize: 26 },

  // Tilt controls column (bottom-right)
  tiltBtnCol: {
    position: 'absolute',
    right: spacing.md,
    alignItems: 'center',
    gap: spacing.xs,
    zIndex: 20,
  },
  tiltBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: NEON,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 10,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
  },
  tiltBtnTxt: { fontSize: 18 },

  // Gemini FAB (bottom-left) — free chat + apps
  geminiLeftFab: {
    position: 'absolute',
    left: spacing.md,
    width: 56,
    height: 56,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 12,
    zIndex: 60,
    borderWidth: 1.5,
  },

  // GPT-4o FAB (bottom-right) — navigation
  geminiFab: {
    position: 'absolute',
    right: spacing.md,
    width: 56,
    height: 56,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 12,
    zIndex: 60,
    borderWidth: 1.5,
  },
  geminiFabOnline:  { backgroundColor: NEON_DIM, borderColor: NEON, shadowColor: NEON, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.85, shadowRadius: 8 },
  geminiFabOffline: { backgroundColor: 'rgba(22,33,62,0.92)', borderColor: colors.border },
  geminiFabEmoji: { fontSize: 24 },

  // Online indicator dot
  onlineDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: colors.bg,
  },
  onlineDotGreen: { backgroundColor: '#22c55e' },
  onlineDotGrey:  { backgroundColor: colors.textMuted },

  // Chat panel
  chatPanel: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    maxHeight: 360,
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 20,
    overflow: 'hidden',
    zIndex: 50,
  },
  chatMessages: {
    flex: 1,
    maxHeight: 280,
  },
  chatMessagesContent: {
    padding: spacing.sm,
    gap: spacing.xs,
  },
  chatPlaceholder: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  chatBubble: {
    maxWidth: '85%',
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    marginBottom: 4,
  },
  chatBubbleUser:  {
    alignSelf: 'flex-end',
    backgroundColor: colors.accent,
  },
  chatBubbleModel: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(50,50,80,0.95)',
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatBubbleText:      { ...typography.caption, color: colors.text, fontSize: 13 },
  chatBubbleTextModel: { ...typography.caption, color: colors.text, fontSize: 16, fontWeight: '700', lineHeight: 22 },

  // Input row
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    gap: spacing.xs,
  },
  chatInput: {
    flex: 1,
    height: 40,
    backgroundColor: 'rgba(15,15,30,0.8)',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    color: colors.text,
    ...typography.caption,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatMicBtn: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: 'rgba(255,59,59,0.10)',
    borderWidth: 1.5,
    borderColor: '#ff3b3b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatMicBtnRecording: {
    backgroundColor: 'rgba(255,59,59,0.35)',
    borderColor: '#ff0000',
    shadowColor: '#ff0000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 8,
  },
  chatMicText: { fontSize: 18 },

  chatSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: NEON,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 6,
  },
  chatSendText: { color: colors.text, fontSize: 16 },

  // ── Fuel cards panel ─────────────────────────────────────────────────────
  fuelPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 19,
  },
  fuelPanelTitle: {
    ...typography.label,
    color: '#00ff88',
    fontWeight: '700',
    fontSize: 12,
  },
  fuelCardBtns: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 6,
  },
  fuelWpBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,191,255,0.10)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 6,
    paddingVertical: 5,
  },
  fuelWpBtnTxt: { color: NEON, fontWeight: '700', fontSize: 10 },
  fuelCard: {
    backgroundColor: 'rgba(0,60,20,0.22)',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginRight: spacing.sm,
    width: 165,
    borderWidth: 2,
    borderColor: '#00ff88',
    elevation: 12,
    shadowColor: '#00ff88',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  fuelCardName: {
    ...typography.label,
    color: colors.text,
    fontWeight: '700',
    fontSize: 12,
    marginBottom: 3,
  },
  fuelCardBrand: {
    ...typography.label,
    color: '#00ff88',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  fuelCardDist: {
    ...typography.label,
    color: NEON,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 5,
  },
  fuelBadge: {
    backgroundColor: 'rgba(0,255,136,0.12)',
    borderRadius: radius.sm,
    paddingHorizontal: 5,
    paddingVertical: 2,
    marginBottom: 3,
    alignSelf: 'flex-start',
  },
  fuelBadgeTruck: {
    backgroundColor: 'rgba(0,191,255,0.12)',
    borderRadius: radius.sm,
    paddingHorizontal: 5,
    paddingVertical: 2,
    marginBottom: 3,
    alignSelf: 'flex-start',
  },
  fuelBadgeTxt: { color: colors.text, fontSize: 9 },
  fuelHours: { ...typography.label, color: colors.textMuted, fontSize: 9, marginBottom: 4 },
  fuelGoTxt: { color: '#00ff88', fontWeight: '800', fontSize: 12, marginTop: 4 },

  // Fuel pins on map
  fuelPin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(245,158,11,0.12)',
    borderWidth: 1.5,
    borderColor: '#f59e0b',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#f59e0b',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  fuelPinText: { fontSize: 16 },

  // Speed camera pins on map
  cameraPin: {
    backgroundColor: 'rgba(30,0,0,0.9)',
    borderRadius: radius.sm,
    padding: 4,
    borderWidth: 1.5,
    borderColor: '#ff3b3b',
    alignItems: 'center',
  },
  cameraPinText: { fontSize: 14 },
  cameraPinSpeed: {
    color: '#ff3b3b',
    fontSize: 8,
    fontWeight: '800',
    marginTop: 1,
  },

  // ── Route options panel ───────────────────────────────────────────────────
  routeOptionsPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: 'rgba(8,16,32,0.78)',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    elevation: 32,
    zIndex: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.45,
    shadowRadius: 24,
    overflow: 'hidden',
  },
  routeOptionsGlassHighlight: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 1,
  },
  routeOptionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xs,
  },
  routeOptionsTitle: {
    ...typography.label,
    color: NEON,
    fontWeight: '700',
    fontSize: 13,
  },
  routeOptionsContent: { paddingHorizontal: spacing.sm, gap: spacing.sm },
  routeOptionCard: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 20,
    padding: spacing.md,
    width: 164,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderTopColor: 'rgba(255,255,255,0.22)',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  routeOptionDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginBottom: 4,
  },
  routeOptionDiff: {
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  routeOptionLabel: {
    ...typography.label,
    color: colors.text,
    fontWeight: '700',
    fontSize: 12,
    marginBottom: 4,
  },
  routeOptionDist: {
    ...typography.label,
    color: NEON,
    fontSize: 13,
    fontWeight: '800',
  },
  routeOptionDur: {
    ...typography.label,
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 2,
  },
  routeOptionTap: {
    color: NEON,
    fontSize: 11,
    fontWeight: '700',
    marginTop: spacing.sm,
    textAlign: 'right',
  },
  routeOptionCardSelected: {
    borderWidth: 1.5,
    borderColor: NEON,
    backgroundColor: 'rgba(0,191,255,0.12)',
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    elevation: 16,
  },
  routeOptionTraffic: {
    fontSize: 10,
    fontWeight: '700',
    color: '#00ff88',
    marginTop: 3,
  },
  routeSelectedSummary: {
    paddingTop: spacing.xs,
    paddingHorizontal: spacing.md,
    gap: 4,
  },
  routeRestrictionWarn: {
    color: '#ffcc00',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  routeStartBtn: {
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 28,
    alignSelf: 'center',
    marginTop: spacing.xs,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 12,
  },
  routeStartBtnTxt: { color: NEON, fontSize: 15, fontWeight: '800' },

  // Origin active badge — shown below SearchBar when custom origin is set
  originActiveBadge: {
    marginTop: 4,
    backgroundColor: 'rgba(0,191,255,0.12)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(0,191,255,0.45)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  originActiveTxt: { color: NEON, fontSize: 11, fontWeight: '600', fontFamily: Platform.OS === 'android' ? 'Roboto' : 'Arial' },

  // ── Tachograph card ──────────────────────────────────────────────────────
  tachPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 19,
  },
  tachTitle: {
    ...typography.label,
    color: '#ffcc00',
    fontWeight: '700',
    fontSize: 12,
  },
  tachCard: {
    marginHorizontal: spacing.md,
    marginTop: spacing.xs,
    backgroundColor: 'rgba(30,20,0,0.88)',
    borderRadius: radius.md,
    padding: spacing.sm,
    borderWidth: 2,
    borderColor: '#ffcc00',
  },
  tachRow: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  tachWarn: {
    color: '#ff3b3b',
    fontWeight: '800',
  },
  tachOk: {
    color: '#4cff91',
    fontWeight: '700',
  },
  tachDivider: {
    height: 1,
    backgroundColor: 'rgba(0,191,255,0.2)',
    marginVertical: 6,
  },
  tachStopBtn: {
    marginTop: spacing.xs,
    backgroundColor: 'rgba(255,204,0,0.18)',
    borderRadius: radius.sm,
    paddingVertical: 6,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: '#ffcc00',
    alignSelf: 'flex-start',
  },
  tachStopTxt: {
    color: '#ffcc00',
    fontWeight: '800',
    fontSize: 12,
  },

  // ── Business / place results panel ───────────────────────────────────────
  bizPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 19,
  },
  bizPanelTitle: {
    ...typography.label,
    color: '#00e5ff',
    fontWeight: '700',
    fontSize: 12,
  },
  bizCard: {
    backgroundColor: 'rgba(0,40,60,0.92)',
    borderRadius: radius.md,
    padding: spacing.sm,
    marginRight: spacing.sm,
    width: 175,
    borderWidth: 2,
    borderColor: '#00e5ff',
    elevation: 12,
    shadowColor: '#00e5ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 8,
  },
  bizCardName: {
    color: colors.text,
    fontWeight: '700',
    fontSize: 13,
    marginBottom: 3,
  },
  bizCardDist: {
    color: '#00e5ff',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 3,
  },
  bizCardAddr: {
    color: colors.textSecondary,
    fontSize: 10,
    marginBottom: 4,
  },
  bizGoTxt: {
    color: '#00e5ff',
    fontWeight: '800',
    fontSize: 12,
    marginTop: 4,
  },
  bizPin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,229,255,0.1)',
    borderWidth: 1.5,
    borderColor: '#00e5ff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#00e5ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 6,
  },
  bizPinText: { fontSize: 18 },
  bizCardPhoto: {
    width: '100%' as const,
    height: 80,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(0,20,40,0.6)',
    marginBottom: 6,
  },
  bizCardClosed: {
    opacity: 0.7,
    borderColor: '#ff6b35',
  },
  bizClosedBadge: {
    backgroundColor: 'rgba(255,107,53,0.18)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginBottom: 4,
  },
  bizClosedBadgeTxt: {
    color: '#ff6b35',
    fontSize: 10,
    fontWeight: '700' as const,
  },
  bizReviewSummary: {
    color: colors.textSecondary,
    fontSize: 10,
    fontStyle: 'italic' as const,
    lineHeight: 14,
    marginTop: 4,
  },

  // ── Options pocket menu ──────────────────────────────────────────────────
  optionsContainer: {
    position: 'absolute',
    right: spacing.md,
    zIndex: 20,
    alignItems: 'flex-end',
  },
  optionsPanel: {
    marginTop: spacing.xs,
    backgroundColor: 'rgba(0,8,20,0.93)',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: NEON,
    padding: spacing.xs,
    gap: spacing.xs,
    elevation: 18,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.85,
    shadowRadius: 10,
  },
  optionsRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  // ── Along Route Sidebar (Step A) ──
  alongRouteSidebar: {
    position: 'absolute',
    right: spacing.md,
    width: 180,
    backgroundColor: 'rgba(0,10,25,0.92)',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: NEON,
    padding: spacing.xs,
    zIndex: 25,
    elevation: 20,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    paddingBottom: 4,
  },
  sidebarTitle: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  sidebarDismiss: { padding: 4 },
  sidebarDismissTxt: { color: colors.textSecondary, fontSize: 12 },
  sidebarContent: { gap: spacing.xs },
  sidebarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 8,
    padding: 6,
    gap: 6,
  },
  sidebarCardEmoji: { fontSize: 16 },
  sidebarCardInfo: { flex: 1 },
  sidebarCardName: { color: '#fff', fontSize: 11, fontWeight: '700' },
  sidebarCardAddr: { color: colors.textSecondary, fontSize: 8 },
  sidebarCardAdd: { color: NEON, fontSize: 12 },

  // ── Route-ahead POI panel ──────────────────────────────────────────────────
  routeAheadPanel: {
    position: 'absolute',
    right: spacing.sm,
    top: '35%',
    flexDirection: 'column',
    gap: 6,
    zIndex: 24,
    elevation: 18,
  },
  routeAheadCard: {
    backgroundColor: 'rgba(0,10,25,0.90)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: NEON,
    paddingHorizontal: 8,
    paddingVertical: 6,
    alignItems: 'center',
    minWidth: 52,
  },
  routeAheadIcon: {
    color: NEON,
    fontSize: 14,
    fontWeight: '900',
  },
  routeAheadKm: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },

  optionBtn: {
    width: 44,
    height: 44,
    borderRadius: 50,
    backgroundColor: NEON_DIM,
    borderWidth: 1.5,
    borderColor: 'rgba(0,191,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionBtnOff: { opacity: 0.3 },
  optionBtnActive: {
    borderColor: NEON,
    backgroundColor: 'rgba(0,191,255,0.22)',
    elevation: 8,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
  },

  // ── SAR (Search Along Route) ────────────────────────────────────────────────
  sarRowLabel: {
    color: NEON,
    fontSize: 10,
    fontWeight: '800' as const,
    letterSpacing: 1.2,
    marginRight: 6,
    alignSelf: 'center',
  },
  sarBtnActive: {
    borderColor: '#ff8c00',
    backgroundColor: 'rgba(255,140,0,0.20)',
    elevation: 8,
    shadowColor: '#ff8c00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
  },
  sarHeaderBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'flex-start' as const,
    backgroundColor: 'rgba(0,8,20,0.90)',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#ff8c00',
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 6,
    marginLeft: spacing.md,
    elevation: 10,
    shadowColor: '#ff8c00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
  },
  sarHeaderTxt: {
    color: '#ff8c00',
    fontSize: 11,
    fontWeight: '700' as const,
  },

  // ── Waypoint map pins ─────────────────────────────────────────────────────
  waypointPin: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,140,0,0.18)',
    borderWidth: 2,
    borderColor: '#ff8c00',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#ff8c00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
  },
  waypointPinBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#ff8c00',
    borderRadius: 8,
    width: 16,
    height: 16,
    fontSize: 10,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    lineHeight: 16,
  },

  // ── Long-press popup — Glassmorphism card ────────────────────────────────
  longPressPopup: {
    position: 'absolute',
    bottom: 150,
    alignSelf: 'center',
    // Glassmorphism base
    backgroundColor: 'rgba(6, 12, 35, 0.85)',
    borderRadius: 18,
    padding: 16,
    paddingTop: 12,
    zIndex: 50,
    elevation: 32,
    minWidth: 270,
    // Neon border glow
    borderWidth: 1,
    borderColor: 'rgba(0,191,255,0.45)',
    // Outer glow
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 14,
  },
  longPressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  longPressTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
    letterSpacing: 0.3,
  },
  longPressCoords: {
    color: 'rgba(0,191,255,0.55)',
    fontSize: 10,
    marginBottom: 14,
    fontFamily: 'monospace',
    letterSpacing: 0.5,
  },
  longPressBtns: {
    flexDirection: 'row',
    gap: 10,
  },
  // Navigate button — neon blue glass pill
  longPressBtn: {
    flex: 1,
    backgroundColor: 'rgba(0,191,255,0.18)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: NEON,
    paddingVertical: 10,
    paddingHorizontal: 12,
    elevation: 4,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  // Waypoint button — orange glass pill
  longPressBtnWaypoint: {
    backgroundColor: 'rgba(255,140,0,0.18)',
    borderColor: '#ff8c00',
    shadowColor: '#ff8c00',
  },
  longPressBtnStar: {
    backgroundColor: 'rgba(255,215,0,0.18)',
    borderColor: '#ffd700',
    shadowColor: '#ffd700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
  },
  longPressBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  longPressBtnTxt: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.3,
  },
  longPressCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Waypoint strip (bottom panel) ─────────────────────────────────────────
  waypointStrip: {
    maxHeight: 42,
    marginBottom: 10,
  },
  waypointStripContent: {
    paddingHorizontal: 4,
    gap: 8,
    alignItems: 'center',
  },
  waypointChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,140,0,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,140,0,0.5)',
    borderRadius: 20,    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
    elevation: 3,
    shadowColor: '#ff8c00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  waypointChipText: {
    color: '#ffaa44',
    fontSize: 12,
    fontWeight: '600',
    maxWidth: 120,
  },
  waypointChipRemove: {
    color: 'rgba(255,107,107,0.85)',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 4,
  },
  waypointChipRemoveBtn: {
    marginLeft: 2,
  },
  optimizeBtn: {
    backgroundColor: 'rgba(0,191,255,0.15)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 14,
    alignSelf: 'center',
    marginTop: 6,
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 6,
  },
  optimizeBtnText: { color: NEON, fontSize: 13, fontWeight: '700' },

  // ── Shared "Go" button for POI cards ─────────────────────────────────────
  goBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: NEON,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    marginTop: 8,
  },
  goBtnFuel: {
    backgroundColor: '#f59e0b',
  },
  goBtnTxt: {
    color: '#0a0c1c',
    fontWeight: '700',
    fontSize: 12,
  },

  // ── Interactive parking bubble (floating over map) ────────────────────────
  parkingBubble: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    backgroundColor: '#0d1e3d',          // тъмно синьо, напълно плътно
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: '#1a8fd1',              // синя рамка
    padding: 13,
    shadowColor: '#1a8fd1',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.90,
    shadowRadius: 14,
    elevation: 22,
  },
  parkingBubbleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  parkingBubbleName: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
    marginRight: 8,
  },
  parkingBubbleClose: { padding: 2 },
  parkingBubbleCloseTxt: { color: 'rgba(255,255,255,0.5)', fontSize: 15 },
  parkingBubbleDist: {
    color: NEON,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  parkingBubbleBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 10,
  },
  pkBadge: {
    backgroundColor: 'rgba(26,143,209,0.20)',   // синкав badge
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(26,143,209,0.45)',
  },
  pkBadgePaid: { backgroundColor: 'rgba(239,68,68,0.22)', borderColor: 'rgba(239,68,68,0.5)' },
  pkBadgeFree: { backgroundColor: 'rgba(34,197,94,0.22)', borderColor: 'rgba(34,197,94,0.5)' },
  pkBadgeTxt: { color: '#e8f4ff', fontSize: 10, fontWeight: '700' },
  parkingBubbleBtns: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  parkingBubbleNavBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: NEON,
    borderRadius: 8,
    paddingVertical: 8,
  },
  parkingBubbleNavBtnTxt: { color: '#0a0c1c', fontWeight: '800', fontSize: 13 },
  parkingBubbleWebBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,191,255,0.12)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 8,
    paddingVertical: 8,
  },
  parkingBubbleWebBtnTxt: { color: NEON, fontWeight: '700', fontSize: 12 },
  parkingBubbleWpBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,191,255,0.12)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 8,
    paddingVertical: 8,
  },
  parkingBubbleWpBtnTxt: { color: NEON, fontWeight: '700', fontSize: 13 },
  parkingBubbleTtsBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Parking card action row ───────────────────────────────────────────────
  parkingCardActions: {
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    marginTop: 'auto' as any,
  },
  parkingGoBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: NEON,
    borderRadius: 6,
    paddingVertical: 5,
  },
  parkingGoBtnTxt2: { color: '#0a0c1c', fontWeight: '800', fontSize: 10 },
  parkingWpBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,191,255,0.10)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 6,
    paddingVertical: 5,
  },
  parkingWpBtnTxt: { color: NEON, fontWeight: '700', fontSize: 10 },
  parkingWebBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,191,255,0.10)',
    borderWidth: 1.5,
    borderColor: NEON,
    borderRadius: 6,
    paddingVertical: 5,
  },
  parkingWebBtnTxt: { color: NEON, fontWeight: '700', fontSize: 10 },
  parkingTtsBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Selected parking pin highlight ───────────────────────────────────────
  parkingPinSelected: {
    backgroundColor: 'rgba(255,59,59,0.25)',
    borderColor: '#ff3b3b',
    borderWidth: 2.5,
    shadowColor: '#ff3b3b',
    shadowOpacity: 0.9,
    shadowRadius: 8,
  },

  // ── Dev tools inside ⚙️ options panel ─────────────────────────────────────
  optionsDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.10)',
    marginVertical: 4,
  },
  devRowLabel: {
    color: 'rgba(255,255,255,0.30)',
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 1.5,
    alignSelf: 'center',
    marginLeft: 4,
  },

  // ── Gemini Connect button in options panel ─────────────────────────────────
  geminiConnectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(0,191,255,0.10)',
    borderWidth: 1.5,
    borderColor: 'rgba(0,191,255,0.45)',
    marginVertical: 2,
    shadowColor: NEON,
    shadowOpacity: 0.55,
    shadowRadius: 6,
  },
  geminiConnectEmoji: { fontSize: 18 },
  geminiConnectLabel: {
    flex: 1,
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  geminiDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4cff91',
    shadowColor: '#4cff91',
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  // kept for state-highlight reuse
  simBtnActive: {
    borderColor: '#ff4444',
    backgroundColor: 'rgba(255,30,30,0.18)',
    shadowColor: '#ff4444',
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },
  simBtnDebug: {
    borderColor: '#ffaa00',
    backgroundColor: 'rgba(255,170,0,0.18)',
    shadowColor: '#ffaa00',
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },

  // ── Visual Debug Overlay ──────────────────────────────────────────────────
  debugOverlay: {
    position: 'absolute',
    left: spacing.md,
    backgroundColor: 'rgba(0,4,12,0.92)',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#ffaa00',
    paddingHorizontal: 10,
    paddingVertical: 8,
    zIndex: 25,
    minWidth: 190,
    shadowColor: '#ffaa00',
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 20,
  },
  debugTitle: {
    color: '#ffaa00',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.5,
    marginBottom: 5,
  },
  debugRow: { color: '#e0e8ff', fontSize: 11, fontWeight: '600', marginBottom: 2 },
  debugLaneTestBtn: {
    marginTop: 6, paddingHorizontal: 10, paddingVertical: 5,
    borderRadius: 8, borderWidth: 1.5, borderColor: 'rgba(0,191,255,0.5)',
    backgroundColor: 'rgba(0,191,255,0.08)',
  },
  debugLaneTestBtnOn: {
    borderColor: NEON,
    backgroundColor: 'rgba(0,191,255,0.30)',
    shadowColor: NEON, shadowOpacity: 0.8, shadowRadius: 6, elevation: 6,
  },
  debugLaneTestTxt: { color: NEON, fontSize: 11, fontWeight: '800' },

  // ── Live Speedometer Ring (replaces speedBox) ─────────────────────────────
  speedRing: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,10,25,0.92)',
    elevation: 12,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
    shadowOpacity: 0.85,
  },
  speedRingGreen:  { borderColor: '#00e676', shadowColor: '#00e676' },
  speedRingYellow: { borderColor: '#ffcc00', shadowColor: '#ffcc00' },
  speedRingRed:    { borderColor: '#ff1744', shadowColor: '#ff1744' },

  parkingHudChip: {
    backgroundColor: 'rgba(0,8,20,0.85)',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(0,191,255,0.4)',
    paddingHorizontal: 8,
    paddingVertical: 5,
    alignItems: 'center',
  },
  parkingHudText: {
    color: NEON,
    fontSize: 12,
    fontWeight: '700',
  },

  // ── Speed Camera HUD ──────────────────────────────────────────────────────
  cameraHUD: {
    position: 'absolute',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 14,
  },

  // ── Weather Pins ──────────────────────────────────────────────────────────
  weatherPin: {
    backgroundColor: 'rgba(0,10,30,0.85)',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: NEON,
    paddingHorizontal: 8,
    paddingVertical: 5,
    alignItems: 'center',
    shadowColor: NEON,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  weatherPinEmoji: { fontSize: 16 },
  weatherPinTemp: { fontSize: 9, color: NEON, fontWeight: '700' },

  // ── NavigationHUD elev + weather sub-styles ───────────────────────────────
  elevProfileStripHUD: { marginTop: 6, paddingHorizontal: 4 },
  elevProfileLabelHUD: { fontSize: 10, color: 'rgba(255,255,255,0.5)', marginBottom: 3 },
  elevProfileBarsHUD: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, height: 32 },
  elevBarHUD: { width: 3, borderRadius: 1, backgroundColor: NEON, opacity: 0.7 },
  weatherStripHUD: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  weatherChipHUD: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(0,10,30,0.7)', borderRadius: 8,
    paddingHorizontal: 7, paddingVertical: 3,
    borderWidth: 1, borderColor: 'rgba(0,247,255,0.2)',
  },

  // ── Camera HUD text sub-styles ────────────────────────────────────────────
  cameraHUDIcon: { fontSize: 24 },
  cameraHUDDist: { fontSize: 18, fontWeight: '900', color: '#FFFFFF' },
  cameraHUDLabel: { fontSize: 10, fontWeight: '700', color: 'rgba(255,255,255,0.7)', letterSpacing: 1 },
});
