import { useNavigationStore } from '../../../store/navigationStore';
export type { NavPhase, RouteOptDest } from '../../../store/navigationStore';

export const useNavigationState = () => {
  const {
    navPhase,
    isNavigating,
    loadingRoute,
    rerouting,
    route,
    setRoute,
    departLabel,
    setDepartLabel,
    currentStepIndex,
    setCurrentStepIndex,
    distToTurn,
    setDistToTurn,
    speedLimit,
    setSpeedLimit,
    remainingSeconds,
    setRemainingSeconds,
    routeOptions,
    setRouteOptions,
    routeOptDest,
    setRouteOptDest,
    selectedRouteIdx,
    setSelectedRouteIdx,
    departAt,
    setDepartAt,
    mapZoom,
    setMapZoom,
    waypoints,
    setWaypoints,
    waypointNames,
    setWaypointNames,
    restrictionChecking,
    setRestrictionChecking,
    restrictionWarnings,
    setRestrictionWarnings,
    avoidUnpaved,
    setAvoidUnpaved,
    setNavPhase,
  } = useNavigationStore();

  return {
    navPhase, setNavPhase,
    navigating: isNavigating,
    loadingRoute,
    rerouting,
    route, setRoute,
    departLabel, setDepartLabel,
    currentStep: currentStepIndex, setCurrentStep: setCurrentStepIndex,
    distToTurn, setDistToTurn,
    speedLimit, setSpeedLimit,
    remainingSeconds, setRemainingSeconds,
    routeOptions, setRouteOptions,
    routeOptDest, setRouteOptDest,
    selectedRouteIdx, setSelectedRouteIdx,
    departAt, setDepartAt,
    mapZoom, setMapZoom,
    waypoints, setWaypoints,
    waypointNames, setWaypointNames,
    restrictionChecking, setRestrictionChecking,
    restrictionWarnings, setRestrictionWarnings,
    avoidUnpaved, setAvoidUnpaved,
  };
};
